sudo: required

language: generic

services: 
 - docker

 before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t skyks4848/docker-react-app3 -f Dockerfile.dev .

script:
  -docker run -e CI=true skyks4848/docker-react-app3 npm run test -- --coverage

after_success:
  -echo "Test success"